# Đổi cổng chạy Backend thành 8080 (Mặc định)
server.port=8080

# Cấu hình Tên Ứng Dụng
spring.application.name=financial-ai-backend

# Bật log hiển thị thông tin chi tiết
logging.level.org.springframework.web=INFO

